export const mockData = {
    rows: [
        {
            id: 138982,
            status: 'published',
            title: 'Chevron закрыла сделку по покупке Hess',
            subtitle:
                'Компания выиграла в споре за ее гайанские активы с ExxonMobil',
            slug: 'chevron-zakryla-sdelku-po-pokupke-hess',
            image: '84316b4c3b8e455195600564b3ef802a/84316b4c3b8e455195600564b3ef802a.webp',
            preview_thumbnail: null,
            image_caption: 'Фото: instagram.com/chevron',
            type_id: 5,
            published_at: '2025-07-19T12:52:05.000Z',
            category_id: 42,
            project_id: 185,
            is_breaking: false,
            is_important: true,
            is_pr: false,
            is_live: false,
            is_commentable: true,
            is_editor_choice: false,
            in_slider: false,
            in_head: false,
            views: 272,
            show_preview: true,
            tts: null,
            is_legacy: false,
            is_green: false,
            source_id: null,
            locale_id: 1,
            translated_article_id: null,
            updated_at: '2025-07-19T15:39:20.000Z',
            tags: [
                {
                    id: 7380,
                    name: 'Hess Corporation',
                    slug: 'hess-corporation',
                    frequency: 2,
                    articles_tags: { article_id: 138982, tag_id: 7380 },
                },
                {
                    id: 12458,
                    name: 'Exxon Mobil Corp',
                    slug: 'exxon-mobil-corp',
                    frequency: 2,
                    articles_tags: { article_id: 138982, tag_id: 12458 },
                },
                {
                    id: 64575,
                    name: 'Hess',
                    slug: 'hess',
                    frequency: 3,
                    articles_tags: { article_id: 138982, tag_id: 64575 },
                },
                {
                    id: 72055,
                    name: 'Chevron Corp.',
                    slug: 'chevron-corp',
                    frequency: 1,
                    articles_tags: { article_id: 138982, tag_id: 72055 },
                },
            ],
            type: { name: 'Новости' },
            category: { id: 42, name: 'В мире', slug: 'world' },
            authors: [],
            people: [],
            locale: { id: 1, name: 'Русский', code: 'ru' },
            translated_article: null,
        },
        {
            id: 138981,
            status: 'published',
            title: 'Третий поток специалистов водной отрасли направили на обучение в Китай',
            subtitle:
                'Всего в этом году курсы повышения квалификации пройдет 121 человек',
            slug: 'tretij-potok-specialistov-vodnoj-otrasli-napravili-na-obuchenie-v-kitaj',
            image: 'f249a437209ad676f4aadd7e3e0db69f/f249a437209ad676f4aadd7e3e0db69f.jpeg',
            preview_thumbnail: null,
            image_caption: 'Фото: министерство водных ресурсов и ирригации',
            type_id: 5,
            published_at: '2025-07-19T10:34:50.000Z',
            category_id: 37,
            project_id: null,
            is_breaking: false,
            is_important: true,
            is_pr: false,
            is_live: false,
            is_commentable: true,
            is_editor_choice: false,
            in_slider: false,
            in_head: false,
            views: 458,
            show_preview: true,
            tts: null,
            is_legacy: false,
            is_green: false,
            source_id: null,
            locale_id: 1,
            translated_article_id: null,
            updated_at: '2025-07-19T15:35:40.000Z',
            tags: [
                {
                    id: 55496,
                    name: 'водные ресурсы Казахстана',
                    slug: 'vodnyye-resursy-kazakhstana',
                    frequency: 33,
                    articles_tags: { article_id: 138981, tag_id: 55496 },
                },
                {
                    id: 65123,
                    name: 'Минводы',
                    slug: 'minvody',
                    frequency: 36,
                    articles_tags: { article_id: 138981, tag_id: 65123 },
                },
                {
                    id: 65623,
                    name: 'Водные объекты',
                    slug: 'vodnyye-ob-yekty',
                    frequency: 8,
                    articles_tags: { article_id: 138981, tag_id: 65623 },
                },
                {
                    id: 68924,
                    name: 'водные проекты',
                    slug: 'vodnyye-proyekty',
                    frequency: 5,
                    articles_tags: { article_id: 138981, tag_id: 68924 },
                },
                {
                    id: 70118,
                    name: 'водные ресурсы ',
                    slug: 'vodnye-resursy',
                    frequency: 9,
                    articles_tags: { article_id: 138981, tag_id: 70118 },
                },
            ],
            type: { name: 'Новости' },
            category: { id: 37, name: 'Государство', slug: 'gosudarstvo' },
            authors: [
                {
                    id: 1769,
                    name: 'Kapital.kz',
                    slug: 'kapitalkz-1769',
                    articles_authors: {
                        article_id: 138981,
                        author_id: 1769,
                    },
                },
            ],
            people: [],
            locale: { id: 1, name: 'Русский', code: 'ru' },
            translated_article: null,
        },
        {
            id: 138980,
            status: 'published',
            title: 'Дональд Трамп утвердил первый в США закон о стейблкоинах',
            subtitle:
                'Подписание он назвал «официальным одобрением» криптоиндустрии со стороны государства',
            slug: 'donald-tramp-utverdil-pervyj-v-ssha-zakon-o-stejblkoinah',
            image: '7ce89109112784c5f8bf2eb478885857/7ce89109112784c5f8bf2eb478885857.webp',
            preview_thumbnail: null,
            image_caption: 'Фото: Руслан Пряников',
            type_id: 5,
            published_at: '2025-07-19T09:02:34.000Z',
            category_id: 17,
            project_id: 185,
            is_breaking: false,
            is_important: true,
            is_pr: false,
            is_live: false,
            is_commentable: true,
            is_editor_choice: false,
            in_slider: false,
            in_head: false,
            views: 533,
            show_preview: true,
            tts: null,
            is_legacy: false,
            is_green: false,
            source_id: null,
            locale_id: 1,
            translated_article_id: null,
            updated_at: '2025-07-19T15:36:09.000Z',
            tags: [
                {
                    id: 44604,
                    name: 'рынок криптовалют',
                    slug: 'rynok-kriptovalyut',
                    frequency: 21,
                    articles_tags: { article_id: 138980, tag_id: 44604 },
                },
                {
                    id: 46819,
                    name: 'крипторынок',
                    slug: 'kriptorynok',
                    frequency: 30,
                    articles_tags: { article_id: 138980, tag_id: 46819 },
                },
                {
                    id: 48361,
                    name: 'криптобиржа',
                    slug: 'kriptobirzha',
                    frequency: 42,
                    articles_tags: { article_id: 138980, tag_id: 48361 },
                },
                {
                    id: 65299,
                    name: 'стейблкоины',
                    slug: 'steyblkoiny',
                    frequency: 3,
                    articles_tags: { article_id: 138980, tag_id: 65299 },
                },
                {
                    id: 66400,
                    name: 'криптовалюта',
                    slug: 'kriptovalyuta',
                    frequency: 461,
                    articles_tags: { article_id: 138980, tag_id: 66400 },
                },
                {
                    id: 71320,
                    name: 'Дональд Трамп ',
                    slug: 'donald-tramp',
                    frequency: 6,
                    articles_tags: { article_id: 138980, tag_id: 71320 },
                },
            ],
            type: { name: 'Новости' },
            category: { id: 17, name: 'Технологии', slug: 'tehnology' },
            authors: [],
            people: [],
            locale: { id: 1, name: 'Русский', code: 'ru' },
            translated_article: null,
        },
        {
            id: 138956,
            status: 'published',
            title: 'Скачок доллара, новая компания Тимура Турлова и внешний долг Казахстана',
            subtitle: 'Интересные новости за неделю на Kapital.kz',
            slug: 'skachok-dollara-novaya-kompaniya-timura-turlova-i-vneshnij-dolg-kazahstana',
            image: '22ecdab4a57d0c7fca4b02679234ccda/22ecdab4a57d0c7fca4b02679234ccda.png',
            preview_thumbnail: null,
            image_caption: 'Kapital.kz',
            type_id: 5,
            published_at: '2025-07-19T08:00:00.000Z',
            category_id: 37,
            project_id: null,
            is_breaking: false,
            is_important: true,
            is_pr: false,
            is_live: false,
            is_commentable: true,
            is_editor_choice: false,
            in_slider: true,
            in_head: false,
            views: 774,
            show_preview: true,
            tts: null,
            is_legacy: false,
            is_green: false,
            source_id: null,
            locale_id: 1,
            translated_article_id: null,
            updated_at: '2025-07-19T15:33:32.000Z',
            tags: [
                {
                    id: 10435,
                    name: 'внешний долг Казахстана',
                    slug: 'vneshniy-dolg-kazakhstana',
                    frequency: 13,
                    articles_tags: { article_id: 138956, tag_id: 10435 },
                },
                {
                    id: 14191,
                    name: 'Тимур Турлов',
                    slug: 'timur-turlov',
                    frequency: 91,
                    articles_tags: { article_id: 138956, tag_id: 14191 },
                },
                {
                    id: 16079,
                    name: 'Тимур Сулейменов',
                    slug: 'timur-suleymenov',
                    frequency: 182,
                    articles_tags: { article_id: 138956, tag_id: 16079 },
                },
                {
                    id: 45875,
                    name: 'базовая ставка',
                    slug: 'bazovaya-stavka',
                    frequency: 409,
                    articles_tags: { article_id: 138956, tag_id: 45875 },
                },
                {
                    id: 58253,
                    name: 'Бекжан Пирматов',
                    slug: 'bekzhan-pirmatov',
                    frequency: 6,
                    articles_tags: { article_id: 138956, tag_id: 58253 },
                },
                {
                    id: 70174,
                    name: 'курс доллара ',
                    slug: 'kurs-dollara',
                    frequency: 12,
                    articles_tags: { article_id: 138956, tag_id: 70174 },
                },
            ],
            type: { name: 'Новости' },
            category: { id: 37, name: 'Государство', slug: 'gosudarstvo' },
            authors: [
                {
                    id: 1769,
                    name: 'Kapital.kz',
                    slug: 'kapitalkz-1769',
                    articles_authors: {
                        article_id: 138956,
                        author_id: 1769,
                    },
                },
            ],
            people: [],
            locale: { id: 1, name: 'Русский', code: 'ru' },
            translated_article: null,
        },
        {
            id: 138979,
            status: 'published',
            title: 'В Актау обсудили вопрос включения шубата в меню нефтяников',
            subtitle:
                'Заместитель акима Мангистауской области Тилек Жеткизгенулы отметил, что эта инициатива поможет' +
                ' развитию сельского хозяйства в регионе',
            slug: 'v-aktau-obsudili-vopros-vklyucheniya-shubata-v-menyu-neftyanikov',
            image: '927f95173f5aeda85f385b309e58ee5e/927f95173f5aeda85f385b309e58ee5e.jpg',
            preview_thumbnail: null,
            image_caption: 'Фото: акимат Мангистауской области',
            type_id: 5,
            published_at: '2025-07-19T07:32:48.000Z',
            category_id: 13,
            project_id: null,
            is_breaking: false,
            is_important: true,
            is_pr: false,
            is_live: false,
            is_commentable: true,
            is_editor_choice: false,
            in_slider: false,
            in_head: false,
            views: 530,
            show_preview: true,
            tts: null,
            is_legacy: false,
            is_green: false,
            source_id: null,
            locale_id: 1,
            translated_article_id: null,
            updated_at: '2025-07-19T15:36:23.000Z',
            tags: [
                {
                    id: 76,
                    name: 'КазМунайГаз',
                    slug: 'kazmunaygaz',
                    frequency: 448,
                    articles_tags: { article_id: 138979, tag_id: 76 },
                },
                {
                    id: 43841,
                    name: 'производство шубата',
                    slug: 'proizvodstvo-shubata',
                    frequency: 1,
                    articles_tags: { article_id: 138979, tag_id: 43841 },
                },
                {
                    id: 46556,
                    name: 'новости Мангистауской области',
                    slug: 'novosti-mangistauskoy-oblasti',
                    frequency: 109,
                    articles_tags: { article_id: 138979, tag_id: 46556 },
                },
                {
                    id: 46817,
                    name: 'сельское хозяйство Казахстана',
                    slug: 'sel-skoye-khozyaystvo-kazakhstana',
                    frequency: 14,
                    articles_tags: { article_id: 138979, tag_id: 46817 },
                },
                {
                    id: 72054,
                    name: 'шубат',
                    slug: 'shubat',
                    frequency: 1,
                    articles_tags: { article_id: 138979, tag_id: 72054 },
                },
            ],
            type: { name: 'Новости' },
            category: { id: 13, name: 'Экономика', slug: 'economic' },
            authors: [
                {
                    id: 1769,
                    name: 'Kapital.kz',
                    slug: 'kapitalkz-1769',
                    articles_authors: {
                        article_id: 138979,
                        author_id: 1769,
                    },
                },
            ],
            people: [],
            locale: { id: 1, name: 'Русский', code: 'ru' },
            translated_article: null,
        },
        {
            id: 138978,
            status: 'published',
            title: 'План борьбы с «черным» рынком воды разработают для Жамбылской области',
            subtitle:
                'Филиал Казводхоза заключил с аграриями региона 3 858 соглашений по подаче воды',
            slug: 'plan-borby-s-chernym-rynkom-vody-razrabotayut-dlya-zhambylskoj-oblasti',
            image: '935e4c49ac126ab4beec4406119e8fe5/935e4c49ac126ab4beec4406119e8fe5.jpeg',
            preview_thumbnail: null,
            image_caption: 'Фото: министерство водных ресурсов и ирригации',
            type_id: 5,
            published_at: '2025-07-19T06:15:25.000Z',
            category_id: 37,
            project_id: null,
            is_breaking: false,
            is_important: true,
            is_pr: false,
            is_live: false,
            is_commentable: true,
            is_editor_choice: false,
            in_slider: true,
            in_head: false,
            views: 659,
            show_preview: true,
            tts: null,
            is_legacy: false,
            is_green: false,
            source_id: null,
            locale_id: 1,
            translated_article_id: null,
            updated_at: '2025-07-19T15:38:27.000Z',
            tags: [
                {
                    id: 15676,
                    name: 'поливная вода',
                    slug: 'polivnaya-voda',
                    frequency: 11,
                    articles_tags: { article_id: 138978, tag_id: 15676 },
                },
                {
                    id: 45807,
                    name: 'новости Жамбылской области',
                    slug: 'novosti-zhambylskoy-oblasti',
                    frequency: 98,
                    articles_tags: { article_id: 138978, tag_id: 45807 },
                },
                {
                    id: 49427,
                    name: 'Нуржан Нуржигитов',
                    slug: 'nurzhan-nurzhigitov',
                    frequency: 50,
                    articles_tags: { article_id: 138978, tag_id: 49427 },
                },
                {
                    id: 65123,
                    name: 'Минводы',
                    slug: 'minvody',
                    frequency: 36,
                    articles_tags: { article_id: 138978, tag_id: 65123 },
                },
                {
                    id: 65610,
                    name: 'Черный рынок воды',
                    slug: 'chernyy-rynok-vody',
                    frequency: 3,
                    articles_tags: { article_id: 138978, tag_id: 65610 },
                },
                {
                    id: 65950,
                    name: 'системы капельного полива',
                    slug: 'sistemy-kapel-nogo-poliva',
                    frequency: 2,
                    articles_tags: { article_id: 138978, tag_id: 65950 },
                },
                {
                    id: 66800,
                    name: 'подготовка к поливному сезону',
                    slug: 'podgotovka-k-polivnomu-sezonu',
                    frequency: 2,
                    articles_tags: { article_id: 138978, tag_id: 66800 },
                },
                {
                    id: 66942,
                    name: 'поливной сезон',
                    slug: 'polivnoy-sezon',
                    frequency: 6,
                    articles_tags: { article_id: 138978, tag_id: 66942 },
                },
                {
                    id: 67349,
                    name: 'подача поливной воды',
                    slug: 'podacha-polivnoy-vody',
                    frequency: 2,
                    articles_tags: { article_id: 138978, tag_id: 67349 },
                },
            ],
            type: { name: 'Новости' },
            category: { id: 37, name: 'Государство', slug: 'gosudarstvo' },
            authors: [
                {
                    id: 1769,
                    name: 'Kapital.kz',
                    slug: 'kapitalkz-1769',
                    articles_authors: {
                        article_id: 138978,
                        author_id: 1769,
                    },
                },
            ],
            people: [],
            locale: { id: 1, name: 'Русский', code: 'ru' },
            translated_article: null,
        },
        {
            id: 138977,
            status: 'published',
            title: 'Новый Налоговый кодекс: норму о СНР разъяснили предпринимателям',
            subtitle: 'Специальные налоговые режимы сократили с семи до трех',
            slug: 'novyj-nalogovyj-kodeks-normu-o-snr-razuyasnili-predprinimatelyam',
            image: '3bea92080e361f5068a91441fdceb0a8/3bea92080e361f5068a91441fdceb0a8.jpg',
            preview_thumbnail: null,
            image_caption: 'primeminister.kz',
            type_id: 5,
            published_at: '2025-07-19T05:13:53.000Z',
            category_id: 13,
            project_id: null,
            is_breaking: false,
            is_important: true,
            is_pr: false,
            is_live: false,
            is_commentable: true,
            is_editor_choice: false,
            in_slider: true,
            in_head: false,
            views: 759,
            show_preview: true,
            tts: null,
            is_legacy: false,
            is_green: false,
            source_id: null,
            locale_id: 1,
            translated_article_id: null,
            updated_at: '2025-07-19T15:34:15.000Z',
            tags: [
                {
                    id: 7858,
                    name: 'Серик Жумангарин',
                    slug: 'serik-zhumangarin',
                    frequency: 210,
                    articles_tags: { article_id: 138977, tag_id: 7858 },
                },
                {
                    id: 14296,
                    name: 'повышение НДС',
                    slug: 'povysheniye-nds',
                    frequency: 34,
                    articles_tags: { article_id: 138977, tag_id: 14296 },
                },
                {
                    id: 21699,
                    name: 'НДС Казахстан',
                    slug: 'nds-kazakhstan',
                    frequency: 27,
                    articles_tags: { article_id: 138977, tag_id: 21699 },
                },
                {
                    id: 47555,
                    name: 'неплательщики НДС',
                    slug: 'neplatel-shchiki-nds',
                    frequency: 8,
                    articles_tags: { article_id: 138977, tag_id: 47555 },
                },
                {
                    id: 62735,
                    name: 'Новый Налоговый кодекс',
                    slug: 'novyy-nalogovyy-kodeks',
                    frequency: 37,
                    articles_tags: { article_id: 138977, tag_id: 62735 },
                },
                {
                    id: 63076,
                    name: 'НПП Атамекен',
                    slug: 'npp-atameken-2',
                    frequency: 24,
                    articles_tags: { article_id: 138977, tag_id: 63076 },
                },
                {
                    id: 64043,
                    name: 'повышение ставки НДС',
                    slug: 'povysheniye-stavki-nds',
                    frequency: 11,
                    articles_tags: { article_id: 138977, tag_id: 64043 },
                },
                {
                    id: 68290,
                    name: 'НДС',
                    slug: 'nds',
                    frequency: 90,
                    articles_tags: { article_id: 138977, tag_id: 68290 },
                },
            ],
            type: { name: 'Новости' },
            category: { id: 13, name: 'Экономика', slug: 'economic' },
            authors: [],
            people: [],
            locale: { id: 1, name: 'Русский', code: 'ru' },
            translated_article: null,
        },
    ],
    limit: 7,
    offset: 1,
    count: 135730,
};
