export const newsMockData = {
    limit: 7,
    offset: 0,
    count: 661,
    rows: [
        {
            id: 138994,
            status: 'published',
            title: 'На бирже доллар продается ниже отметки 530 тенге  ',
            subtitle:
                'В обменных пунктах Астаны максимальный курс продажи американской' +
                ' валюты составил 537 тенге, Алматы – 533,5 тенге',
            slug: 'na-birzhe-dollar-prodaetsya-nizhe-otmetki-530-tenge',
            image: '0cfcebcb808209f347fbecc31ff22c9c/0cfcebcb808209f347fbecc31ff22c9c.webp',
            preview_thumbnail: null,
            image_caption: '',
            type_id: 5,
            published_at: '2025-07-21T06:15:58.000Z',
            category_id: 14,
            project_id: null,
            is_breaking: false,
            is_important: true,
            is_pr: false,
            is_live: false,
            is_commentable: true,
            is_editor_choice: false,
            in_slider: false,
            in_head: false,
            views: 358,
            show_preview: true,
            tts: null,
            is_legacy: false,
            is_green: false,
            source_id: null,
            locale_id: 1,
            translated_article_id: null,
            updated_at: '2025-07-21T08:35:37.000Z',
            type: {
                name: 'Новости',
            },
            category: {
                id: 14,
                name: 'Финансы',
                slug: 'finance',
            },
            authors: [],
            locale: {
                id: 1,
                name: 'Русский',
                code: 'ru',
            },
            people: [],
            tags: [
                {
                    id: 186,
                    name: 'торги',
                    slug: 'torgi',
                    frequency: 269,
                    articles_tags: {
                        article_id: 138994,
                        tag_id: 186,
                    },
                },
                {
                    id: 21408,
                    name: 'доллар тенге',
                    slug: 'dollar-tenge',
                    frequency: 25,
                    articles_tags: {
                        article_id: 138994,
                        tag_id: 21408,
                    },
                },
                {
                    id: 73,
                    name: 'KASE',
                    slug: 'kase',
                    frequency: 661,
                    articles_tags: {
                        article_id: 138994,
                        tag_id: 73,
                    },
                },
            ],
        },
        {
            id: 138902,
            status: 'published',
            title: 'На бирже доллар продается выше отметки 531 тенге  ',
            subtitle:
                'В обменных пунктах Астаны максимальный курс продажи американской' +
                ' валюты составил 534 тенге, Алматы – 535 тенге',
            slug: 'na-birzhe-dollar-prodaetsya-vyshe-otmetki-531-tenge',
            image: 'ed84f49f8e8bd297c8b4cd7d9fd66176/ed84f49f8e8bd297c8b4cd7d9fd66176.jpg',
            preview_thumbnail: null,
            image_caption: 'Фото: Валерия Змейкова ',
            type_id: 5,
            published_at: '2025-07-17T06:15:33.000Z',
            category_id: 14,
            project_id: null,
            is_breaking: false,
            is_important: true,
            is_pr: false,
            is_live: false,
            is_commentable: true,
            is_editor_choice: false,
            in_slider: false,
            in_head: false,
            views: 1682,
            show_preview: true,
            tts: null,
            is_legacy: false,
            is_green: false,
            source_id: null,
            locale_id: 1,
            translated_article_id: null,
            updated_at: '2025-07-21T09:00:50.000Z',
            type: {
                name: 'Новости',
            },
            category: {
                id: 14,
                name: 'Финансы',
                slug: 'finance',
            },
            authors: [],
            locale: {
                id: 1,
                name: 'Русский',
                code: 'ru',
            },
            people: [],
            tags: [
                {
                    id: 73,
                    name: 'KASE',
                    slug: 'kase',
                    frequency: 661,
                    articles_tags: {
                        article_id: 138902,
                        tag_id: 73,
                    },
                },
                {
                    id: 186,
                    name: 'торги',
                    slug: 'torgi',
                    frequency: 269,
                    articles_tags: {
                        article_id: 138902,
                        tag_id: 186,
                    },
                },
                {
                    id: 44443,
                    name: 'тенге-доллар',
                    slug: 'tenge-dollar',
                    frequency: 1251,
                    articles_tags: {
                        article_id: 138902,
                        tag_id: 44443,
                    },
                },
            ],
        },
        {
            id: 138868,
            status: 'published',
            title: 'KASE представила итоги работы за первое полугодие 2025 года',
            subtitle:
                'Совокупный объем торгов составил 176,1 трлн тенге и снизился по ' +
                'сравнению с аналогичным периодом 2024 года на 5,9% ',
            slug: 'kase-predstavila-itogi-raboty-za-pervoe-polugodie-2025-goda',
            image: '9091682969101e382545b408c6ccf13f/9091682969101e382545b408c6ccf13f.png',
            preview_thumbnail: null,
            image_caption: '',
            type_id: 5,
            published_at: '2025-07-16T10:07:42.000Z',
            category_id: 14,
            project_id: 185,
            is_breaking: false,
            is_important: true,
            is_pr: false,
            is_live: false,
            is_commentable: true,
            is_editor_choice: false,
            in_slider: false,
            in_head: false,
            views: 1663,
            show_preview: true,
            tts: null,
            is_legacy: false,
            is_green: false,
            source_id: null,
            locale_id: 1,
            translated_article_id: null,
            updated_at: '2025-07-21T07:35:23.000Z',
            type: {
                name: 'Новости',
            },
            category: {
                id: 14,
                name: 'Финансы',
                slug: 'finance',
            },
            authors: [
                {
                    name: 'Kapital.kz',
                    slug: 'kapitalkz-1769',
                    articles_authors: {
                        article_id: 138868,
                        author_id: 1769,
                    },
                },
            ],
            locale: {
                id: 1,
                name: 'Русский',
                code: 'ru',
            },
            people: [],
            tags: [
                {
                    id: 73,
                    name: 'KASE',
                    slug: 'kase',
                    frequency: 661,
                    articles_tags: {
                        article_id: 138868,
                        tag_id: 73,
                    },
                },
                {
                    id: 3278,
                    name: 'Казахстанская фондовая биржа',
                    slug: 'kazakhstanskaya-fondovaya-birzha',
                    frequency: 137,
                    articles_tags: {
                        article_id: 138868,
                        tag_id: 3278,
                    },
                },
                {
                    id: 44576,
                    name: 'биржа KASE',
                    slug: 'birzha-kase',
                    frequency: 4,
                    articles_tags: {
                        article_id: 138868,
                        tag_id: 44576,
                    },
                },
                {
                    id: 45079,
                    name: 'Торги на KASE',
                    slug: 'torgi-na-kase',
                    frequency: 1880,
                    articles_tags: {
                        article_id: 138868,
                        tag_id: 45079,
                    },
                },
                {
                    id: 47935,
                    name: 'Адиль Мухамеджанов',
                    slug: 'adil-mukhamedzhanov',
                    frequency: 12,
                    articles_tags: {
                        article_id: 138868,
                        tag_id: 47935,
                    },
                },
                {
                    id: 53878,
                    name: 'KASE Global',
                    slug: 'kase-global',
                    frequency: 47,
                    articles_tags: {
                        article_id: 138868,
                        tag_id: 53878,
                    },
                },
                {
                    id: 67809,
                    name: 'итоги полугодия',
                    slug: 'itogi-polugodiya',
                    frequency: 4,
                    articles_tags: {
                        article_id: 138868,
                        tag_id: 67809,
                    },
                },
            ],
        },
        {
            id: 138861,
            status: 'published',
            title: 'За второй квартал 2025 года Индекс KASE вырос на 6,4%',
            subtitle:
                'Наибольший объем торгов пришелся на простые акции Казахтелекома',
            slug: 'za-vtoroj-kvartal-2025-goda-indeks-kase-vyros-na-64percent',
            image: 'da9ed8fcbe3bb4cdc9d568f1c55f67fe/da9ed8fcbe3bb4cdc9d568f1c55f67fe.JPG',
            preview_thumbnail: null,
            image_caption: 'Фото: Руслан Пряников',
            type_id: 5,
            published_at: '2025-07-16T07:43:24.000Z',
            category_id: 14,
            project_id: 185,
            is_breaking: false,
            is_important: true,
            is_pr: false,
            is_live: false,
            is_commentable: true,
            is_editor_choice: false,
            in_slider: true,
            in_head: false,
            views: 1320,
            show_preview: true,
            tts: null,
            is_legacy: false,
            is_green: false,
            source_id: null,
            locale_id: 1,
            translated_article_id: null,
            updated_at: '2025-07-21T07:38:22.000Z',
            type: {
                name: 'Новости',
            },
            category: {
                id: 14,
                name: 'Финансы',
                slug: 'finance',
            },
            authors: [
                {
                    name: 'Kapital.kz',
                    slug: 'kapitalkz-1769',
                    articles_authors: {
                        article_id: 138861,
                        author_id: 1769,
                    },
                },
            ],
            locale: {
                id: 1,
                name: 'Русский',
                code: 'ru',
            },
            people: [],
            tags: [
                {
                    id: 16204,
                    name: 'фондовые индексы',
                    slug: 'fondovyye-indeksy',
                    frequency: 8,
                    articles_tags: {
                        article_id: 138861,
                        tag_id: 16204,
                    },
                },
                {
                    id: 67648,
                    name: 'фондовый рынок',
                    slug: 'fondovyy-rynok-2',
                    frequency: 196,
                    articles_tags: {
                        article_id: 138861,
                        tag_id: 67648,
                    },
                },
                {
                    id: 45689,
                    name: 'торги акциями',
                    slug: 'torgi-aktsiyami',
                    frequency: 30,
                    articles_tags: {
                        article_id: 138861,
                        tag_id: 45689,
                    },
                },
                {
                    id: 5560,
                    name: 'индекс KASE',
                    slug: 'indeks-kase',
                    frequency: 70,
                    articles_tags: {
                        article_id: 138861,
                        tag_id: 5560,
                    },
                },
                {
                    id: 3278,
                    name: 'Казахстанская фондовая биржа',
                    slug: 'kazakhstanskaya-fondovaya-birzha',
                    frequency: 137,
                    articles_tags: {
                        article_id: 138861,
                        tag_id: 3278,
                    },
                },
                {
                    id: 73,
                    name: 'KASE',
                    slug: 'kase',
                    frequency: 661,
                    articles_tags: {
                        article_id: 138861,
                        tag_id: 73,
                    },
                },
            ],
        },
        {
            id: 138734,
            status: 'published',
            title: 'Какие планы у Нацбанка на KASE и AIX  ',
            subtitle:
                'О физическом объединении инфраструктурных площадок речи не идет, заявил Тимур Сулейменов',
            slug: 'kakie-plany-u-nacbanka-na-kase-i-aix',
            image: '358c8a62b4125fc1d19a051702cfb1c7/358c8a62b4125fc1d19a051702cfb1c7.webp',
            preview_thumbnail: null,
            image_caption: 'Kapital.kz',
            type_id: 5,
            published_at: '2025-07-11T11:40:39.000Z',
            category_id: 14,
            project_id: null,
            is_breaking: false,
            is_important: true,
            is_pr: false,
            is_live: false,
            is_commentable: true,
            is_editor_choice: false,
            in_slider: false,
            in_head: false,
            views: 2768,
            show_preview: true,
            tts: null,
            is_legacy: false,
            is_green: false,
            source_id: null,
            locale_id: 1,
            translated_article_id: null,
            updated_at: '2025-07-21T08:04:36.000Z',
            type: {
                name: 'Новости',
            },
            category: {
                id: 14,
                name: 'Финансы',
                slug: 'finance',
            },
            authors: [
                {
                    name: 'Арсен Аскаров',
                    slug: 'arsen-askarov-1461',
                    articles_authors: {
                        article_id: 138734,
                        author_id: 1461,
                    },
                },
            ],
            locale: {
                id: 1,
                name: 'Русский',
                code: 'ru',
            },
            people: [],
            tags: [
                {
                    id: 73,
                    name: 'KASE',
                    slug: 'kase',
                    frequency: 661,
                    articles_tags: {
                        article_id: 138734,
                        tag_id: 73,
                    },
                },
                {
                    id: 46175,
                    name: 'AIX',
                    slug: 'aix',
                    frequency: 106,
                    articles_tags: {
                        article_id: 138734,
                        tag_id: 46175,
                    },
                },
                {
                    id: 70331,
                    name: 'объединение ',
                    slug: 'obuedinenie',
                    frequency: 2,
                    articles_tags: {
                        article_id: 138734,
                        tag_id: 70331,
                    },
                },
            ],
        },
        {
            id: 138689,
            status: 'published',
            title: 'Казхром покидает KASE ',
            subtitle: 'Это решение одобрено акционерами единогласно ',
            slug: 'kazhrom-pokidaet-kase',
            image: '7b13a9264d387d075a0d684a5ae2e985/7b13a9264d387d075a0d684a5ae2e985.png',
            preview_thumbnail: null,
            image_caption: 'Фото: сайт ТНК «Казхром»',
            type_id: 5,
            published_at: '2025-07-10T09:33:23.000Z',
            category_id: 14,
            project_id: 185,
            is_breaking: false,
            is_important: true,
            is_pr: false,
            is_live: false,
            is_commentable: true,
            is_editor_choice: false,
            in_slider: true,
            in_head: false,
            views: 3122,
            show_preview: true,
            tts: null,
            is_legacy: false,
            is_green: false,
            source_id: null,
            locale_id: 1,
            translated_article_id: null,
            updated_at: '2025-07-21T07:37:39.000Z',
            type: {
                name: 'Новости',
            },
            category: {
                id: 14,
                name: 'Финансы',
                slug: 'finance',
            },
            authors: [
                {
                    name: 'Анна Видянова',
                    slug: 'anna-vidyanova-1875',
                    articles_authors: {
                        article_id: 138689,
                        author_id: 1875,
                    },
                },
            ],
            locale: {
                id: 1,
                name: 'Русский',
                code: 'ru',
            },
            people: [],
            tags: [
                {
                    id: 73,
                    name: 'KASE',
                    slug: 'kase',
                    frequency: 661,
                    articles_tags: {
                        article_id: 138689,
                        tag_id: 73,
                    },
                },
                {
                    id: 12905,
                    name: 'делистинг',
                    slug: 'delisting',
                    frequency: 21,
                    articles_tags: {
                        article_id: 138689,
                        tag_id: 12905,
                    },
                },
                {
                    id: 45882,
                    name: 'ERG',
                    slug: 'erg',
                    frequency: 44,
                    articles_tags: {
                        article_id: 138689,
                        tag_id: 45882,
                    },
                },
                {
                    id: 70239,
                    name: 'акции',
                    slug: 'akcii',
                    frequency: 9,
                    articles_tags: {
                        article_id: 138689,
                        tag_id: 70239,
                    },
                },
                {
                    id: 71213,
                    name: 'Казхром',
                    slug: 'kazhrom',
                    frequency: 4,
                    articles_tags: {
                        article_id: 138689,
                        tag_id: 71213,
                    },
                },
            ],
        },
        {
            id: 138676,
            status: 'published',
            title: 'Объединение KASE и AIX приостановлено',
            subtitle: 'Биржи сохранят текущую структуру и функционал',
            slug: 'obuedinenie-kase-i-aix-priostanovleno',
            image: '713736e1c388b2920cfe3eec1bdc8eb7/713736e1c388b2920cfe3eec1bdc8eb7.jpg',
            preview_thumbnail: null,
            image_caption: 'Kapital.kz',
            type_id: 5,
            published_at: '2025-07-10T07:37:00.000Z',
            category_id: 14,
            project_id: null,
            is_breaking: false,
            is_important: true,
            is_pr: false,
            is_live: false,
            is_commentable: true,
            is_editor_choice: false,
            in_slider: false,
            in_head: false,
            views: 2843,
            show_preview: true,
            tts: null,
            is_legacy: false,
            is_green: false,
            source_id: null,
            locale_id: 1,
            translated_article_id: null,
            updated_at: '2025-07-21T07:34:38.000Z',
            type: {
                name: 'Новости',
            },
            category: {
                id: 14,
                name: 'Финансы',
                slug: 'finance',
            },
            authors: [],
            locale: {
                id: 1,
                name: 'Русский',
                code: 'ru',
            },
            people: [],
            tags: [
                {
                    id: 73,
                    name: 'KASE',
                    slug: 'kase',
                    frequency: 661,
                    articles_tags: {
                        article_id: 138676,
                        tag_id: 73,
                    },
                },
                {
                    id: 3278,
                    name: 'Казахстанская фондовая биржа',
                    slug: 'kazakhstanskaya-fondovaya-birzha',
                    frequency: 137,
                    articles_tags: {
                        article_id: 138676,
                        tag_id: 3278,
                    },
                },
                {
                    id: 46175,
                    name: 'AIX',
                    slug: 'aix',
                    frequency: 106,
                    articles_tags: {
                        article_id: 138676,
                        tag_id: 46175,
                    },
                },
                {
                    id: 47070,
                    name: 'Astana International Exchange',
                    slug: 'astana-international-exchange',
                    frequency: 22,
                    articles_tags: {
                        article_id: 138676,
                        tag_id: 47070,
                    },
                },
                {
                    id: 71896,
                    name: 'объединение KASE и AIX',
                    slug: 'obuedinenie-kase-i-aix',
                    frequency: 1,
                    articles_tags: {
                        article_id: 138676,
                        tag_id: 71896,
                    },
                },
            ],
        },
    ],
    tag: {
        id: 73,
        name: 'KASE',
        description:
            'Казахстанская фондовая биржа (Kazakhstan Stock Exchange — KASE) —' +
            ' фондовая биржа со штаб-квартирой в городе Алматы, Казахстан, занимает ' +
            'второе место среди бирж СНГ по капитализации рынка акций. Была основана в 1993 году.',
        slug: 'kase',
        frequency: 661,
        is_supertag: false,
        parent_id: null,
        meta: {},
        updated_at: '2025-07-21T06:12:09.000Z',
        parent: null,
    },
};

export const popularNewsMockData = {
    rows: [
        {
            id: 139001,
            status: 'published',
            title: 'Казахстанские карты стали активнее за рубежом: оборот составил рекордные 2 трлн тенге',
            subtitle: 'За год показатель вырос на 38%',
            slug: 'kazahstanskie-karty-stali-aktivnee-za-rubezhom-oborot-sostavil-rekordnye-2-trln-tenge',
            image: '2e3a988f15df3ce3e03923e431982c71/2e3a988f15df3ce3e03923e431982c71.webp',
            preview_thumbnail: null,
            image_caption: 'Kapital.kz',
            type_id: 5,
            published_at: '2025-07-21T08:53:38.000Z',
            category_id: 14,
            project_id: null,
            is_breaking: false,
            is_important: true,
            is_pr: false,
            is_live: false,
            is_commentable: true,
            is_editor_choice: false,
            in_slider: false,
            in_head: false,
            views: 60,
            show_preview: true,
            tts: null,
            is_legacy: false,
            is_green: false,
            source_id: null,
            locale_id: 1,
            translated_article_id: null,
            updated_at: '2025-07-21T09:02:36.000Z',
            tags: [
                {
                    id: 6514,
                    name: 'оборот',
                    slug: 'oborot',
                    frequency: 3,
                    articles_tags: {
                        article_id: 139001,
                        tag_id: 6514,
                    },
                },
                {
                    id: 70098,
                    name: 'Казахстан ',
                    slug: 'kazahstan',
                    frequency: 174,
                    articles_tags: {
                        article_id: 139001,
                        tag_id: 70098,
                    },
                },
                {
                    id: 72072,
                    name: 'платежные карты ',
                    slug: 'platezhnye-karty',
                    frequency: 1,
                    articles_tags: {
                        article_id: 139001,
                        tag_id: 72072,
                    },
                },
                {
                    id: 72073,
                    name: 'зарубежье ',
                    slug: 'zarubezhe',
                    frequency: 1,
                    articles_tags: {
                        article_id: 139001,
                        tag_id: 72073,
                    },
                },
            ],
            type: {
                name: 'Новости',
            },
            category: {
                id: 14,
                name: 'Финансы',
                slug: 'finance',
            },
            authors: [],
            people: [],
            locale: {
                id: 1,
                name: 'Русский',
                code: 'ru',
            },
            translated_article: null,
        },
        {
            id: 138999,
            status: 'published',
            title: 'Осуждены участники мошенничества с жильем для переселенцев в Павлодарской области ',
            subtitle:
                'Переселенцам ставили условия - завысить в договоре купли-продажи стоимость жилья ',
            slug: 'osuzhdeny-uchastniki-moshennichestva-s-zhilem-dlya-pereselencev-v-pavlodarskoj-oblasti',
            image: 'a537cf6accaa8af6335fc61bf5944fb9/a537cf6accaa8af6335fc61bf5944fb9.webp',
            preview_thumbnail: null,
            image_caption: 'Kapital.kz',
            type_id: 5,
            published_at: '2025-07-21T08:44:06.000Z',
            category_id: 37,
            project_id: null,
            is_breaking: false,
            is_important: true,
            is_pr: false,
            is_live: false,
            is_commentable: true,
            is_editor_choice: false,
            in_slider: false,
            in_head: false,
            views: 0,
            show_preview: true,
            tts: null,
            is_legacy: false,
            is_green: false,
            source_id: null,
            locale_id: 1,
            translated_article_id: null,
            updated_at: '2025-07-21T08:52:46.000Z',
            tags: [
                {
                    id: 486,
                    name: 'Павлодарская область',
                    slug: 'pavlodarskaya-oblast',
                    frequency: 60,
                    articles_tags: {
                        article_id: 138999,
                        tag_id: 486,
                    },
                },
                {
                    id: 70692,
                    name: 'переселенцы ',
                    slug: 'pereselency',
                    frequency: 2,
                    articles_tags: {
                        article_id: 138999,
                        tag_id: 70692,
                    },
                },
                {
                    id: 71205,
                    name: 'коррупция ',
                    slug: 'korrupciya',
                    frequency: 2,
                    articles_tags: {
                        article_id: 138999,
                        tag_id: 71205,
                    },
                },
                {
                    id: 71890,
                    name: 'трудовая мобильность ',
                    slug: 'trudovaya-mobilnost',
                    frequency: 2,
                    articles_tags: {
                        article_id: 138999,
                        tag_id: 71890,
                    },
                },
                {
                    id: 72071,
                    name: 'Успенский район ',
                    slug: 'uspenskij-rajon',
                    frequency: 1,
                    articles_tags: {
                        article_id: 138999,
                        tag_id: 72071,
                    },
                },
            ],
            type: {
                name: 'Новости',
            },
            category: {
                id: 37,
                name: 'Государство',
                slug: 'gosudarstvo',
            },
            authors: [],
            people: [],
            locale: {
                id: 1,
                name: 'Русский',
                code: 'ru',
            },
            translated_article: null,
        },
        {
            id: 138998,
            status: 'published',
            title: 'Ключевым фактором роста промышленности в Казахстане остается нефтяной сектор ',
            subtitle: 'Эксперт прогнозирует замедление во втором полугодии  ',
            slug: 'klyuchevym-faktorom-rosta-promyshlennosti-v-kazahstane-ostaetsya-neftyanoj-sektor',
            image: '947a13d2842e067e0cd53629211b69de/947a13d2842e067e0cd53629211b69de.webp',
            preview_thumbnail: null,
            image_caption: 'Kapital.kz',
            type_id: 5,
            published_at: '2025-07-21T07:45:52.000Z',
            category_id: 13,
            project_id: null,
            is_breaking: false,
            is_important: true,
            is_pr: false,
            is_live: false,
            is_commentable: true,
            is_editor_choice: false,
            in_slider: true,
            in_head: false,
            views: 190,
            show_preview: true,
            tts: null,
            is_legacy: false,
            is_green: false,
            source_id: null,
            locale_id: 1,
            translated_article_id: null,
            updated_at: '2025-07-21T08:37:02.000Z',
            tags: [
                {
                    id: 72068,
                    name: 'Промышленный рост ',
                    slug: 'promyshlennyj-rost',
                    frequency: 1,
                    articles_tags: {
                        article_id: 138998,
                        tag_id: 72068,
                    },
                },
                {
                    id: 72069,
                    name: 'недропользование ',
                    slug: 'nedropolzovanie',
                    frequency: 1,
                    articles_tags: {
                        article_id: 138998,
                        tag_id: 72069,
                    },
                },
                {
                    id: 72070,
                    name: 'нефтяной сектор ',
                    slug: 'neftyanoj-sektor',
                    frequency: 1,
                    articles_tags: {
                        article_id: 138998,
                        tag_id: 72070,
                    },
                },
            ],
            type: {
                name: 'Новости',
            },
            category: {
                id: 13,
                name: 'Экономика',
                slug: 'economic',
            },
            authors: [],
            people: [],
            locale: {
                id: 1,
                name: 'Русский',
                code: 'ru',
            },
            translated_article: null,
        },
        {
            id: 138997,
            status: 'published',
            title: 'Пожар на складе в Алматы локализован ',
            subtitle:
                'По предварительным данным, возгорание ликвидировано на площади 500 квадратных метров',
            slug: 'pozhar-na-sklade-v-almaty-lokalizovan',
            image: '52111e62baaf1bf24feeabdb8527f694/52111e62baaf1bf24feeabdb8527f694.png',
            preview_thumbnail: null,
            image_caption: 'Фото: Министерство по ЧС РК ',
            type_id: 5,
            published_at: '2025-07-21T06:58:49.000Z',
            category_id: 37,
            project_id: null,
            is_breaking: false,
            is_important: true,
            is_pr: false,
            is_live: false,
            is_commentable: true,
            is_editor_choice: false,
            in_slider: false,
            in_head: false,
            views: 292,
            show_preview: true,
            tts: null,
            is_legacy: false,
            is_green: false,
            source_id: null,
            locale_id: 1,
            translated_article_id: null,
            updated_at: '2025-07-21T09:00:33.000Z',
            tags: [
                {
                    id: 3436,
                    name: 'МЧС',
                    slug: 'mchs',
                    frequency: 102,
                    articles_tags: {
                        article_id: 138997,
                        tag_id: 3436,
                    },
                },
                {
                    id: 10029,
                    name: 'пожар',
                    slug: 'pozhar',
                    frequency: 271,
                    articles_tags: {
                        article_id: 138997,
                        tag_id: 10029,
                    },
                },
                {
                    id: 61490,
                    name: 'склад',
                    slug: 'sklad',
                    frequency: 8,
                    articles_tags: {
                        article_id: 138997,
                        tag_id: 61490,
                    },
                },
                {
                    id: 68519,
                    name: 'Алматы',
                    slug: 'almaty',
                    frequency: 382,
                    articles_tags: {
                        article_id: 138997,
                        tag_id: 68519,
                    },
                },
                {
                    id: 72066,
                    name: 'тушение ',
                    slug: 'tushenie',
                    frequency: 1,
                    articles_tags: {
                        article_id: 138997,
                        tag_id: 72066,
                    },
                },
                {
                    id: 72067,
                    name: 'локализация ',
                    slug: 'lokalizaciya',
                    frequency: 1,
                    articles_tags: {
                        article_id: 138997,
                        tag_id: 72067,
                    },
                },
            ],
            type: {
                name: 'Новости',
            },
            category: {
                id: 37,
                name: 'Государство',
                slug: 'gosudarstvo',
            },
            authors: [],
            people: [],
            locale: {
                id: 1,
                name: 'Русский',
                code: 'ru',
            },
            translated_article: null,
        },
        {
            id: 138996,
            status: 'published',
            title: 'Переезд воспитанников детского дома Баганашыл из Алматы в Конаев отменил президент ',
            subtitle:
                'По данному делу Администрация президента проведет служебное расследование ',
            slug: 'pereezd-vospitannikov-detskogo-doma-baganashyl-iz-almaty-v-konaev-otmenil-prezident',
            image: 'bb71018283a7abf3b7705c1d68b0bd2c/bb71018283a7abf3b7705c1d68b0bd2c.webp',
            preview_thumbnail: null,
            image_caption: 'Фото: Руслан Пряников',
            type_id: 5,
            published_at: '2025-07-21T06:44:35.000Z',
            category_id: 37,
            project_id: null,
            is_breaking: false,
            is_important: true,
            is_pr: false,
            is_live: false,
            is_commentable: true,
            is_editor_choice: false,
            in_slider: false,
            in_head: false,
            views: 378,
            show_preview: true,
            tts: null,
            is_legacy: false,
            is_green: false,
            source_id: null,
            locale_id: 1,
            translated_article_id: null,
            updated_at: '2025-07-21T08:36:47.000Z',
            tags: [
                {
                    id: 96,
                    name: 'президент',
                    slug: 'prezident',
                    frequency: 309,
                    articles_tags: {
                        article_id: 138996,
                        tag_id: 96,
                    },
                },
                {
                    id: 1468,
                    name: 'отмена',
                    slug: 'otmena',
                    frequency: 52,
                    articles_tags: {
                        article_id: 138996,
                        tag_id: 1468,
                    },
                },
                {
                    id: 70216,
                    name: 'переезд ',
                    slug: 'pereezd',
                    frequency: 2,
                    articles_tags: {
                        article_id: 138996,
                        tag_id: 70216,
                    },
                },
                {
                    id: 72063,
                    name: 'детский дом ',
                    slug: 'detskij-dom',
                    frequency: 1,
                    articles_tags: {
                        article_id: 138996,
                        tag_id: 72063,
                    },
                },
                {
                    id: 72064,
                    name: 'воспитанники ',
                    slug: 'vospitanniki',
                    frequency: 1,
                    articles_tags: {
                        article_id: 138996,
                        tag_id: 72064,
                    },
                },
                {
                    id: 72065,
                    name: 'служебное расследование ',
                    slug: 'sluzhebnoe-rassledovanie',
                    frequency: 1,
                    articles_tags: {
                        article_id: 138996,
                        tag_id: 72065,
                    },
                },
            ],
            type: {
                name: 'Новости',
            },
            category: {
                id: 37,
                name: 'Государство',
                slug: 'gosudarstvo',
            },
            authors: [],
            people: [],
            locale: {
                id: 1,
                name: 'Русский',
                code: 'ru',
            },
            translated_article: null,
        },
    ],
    limit: 5,
    offset: 0,
    count: 238,
};
